# Generated by Django 6.0.1 on 2026-05-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de l'événement"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Type d'événement",
                "verbose_name_plural": "Types d'événements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        default="", max_length=200, verbose_name="Nom complet"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(default="", max_length=254, verbose_name="Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du projet"),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "event_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de l'événement"
                    ),
                ),
                (
                    "event_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de l'événement"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Lieu précis"
                    ),
                ),
                (
                    "guest_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nombre d'invités estimé"
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget minimum (FCFA)",
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget maximum (FCFA)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle demande"),
                            ("contacted", "Contacté"),
                            ("in_progress", "En cours"),
                            ("closed", "Clôturé"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.eventtype",
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "services_needed",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="vendors.servicetype",
                        verbose_name="Services recherchés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande client",
                "verbose_name_plural": "Demandes clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("call", "Appel"),
                            ("meeting", "Réunion"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
