# Generated by Django 6.0.1 on 2026-01-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("published", "Publié"),
                    ("in_progress", "En cours"),
                    ("completed", "Terminé"),
                    ("cancelled", "Annulé"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
