# Generated by Django 6.0.1 on 2026-01-18 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_created_at_alter_project_status"),
        ("vendors", "0011_alter_vendorprofile_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        help_text="Pourquoi ce prestataire est recommandé pour ce projet",
                        verbose_name="Note de Suzy",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("sent", "Envoyée"),
                            ("viewed", "Vue"),
                            ("contacted", "Contacté"),
                            ("accepted", "Acceptée"),
                            ("declined", "Déclinée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Envoyée le"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Vue le"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recommandé par",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_recommendations",
                        to="vendors.vendorprofile",
                        verbose_name="Prestataire recommandé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation Suzy",
                "verbose_name_plural": "Recommandations Suzy",
                "ordering": ["-created_at"],
                "unique_together": {("project", "vendor")},
            },
        ),
    ]
