# Generated by Django 6.0.1 on 2026-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Email"
            ),
        ),
    ]
