# Generated by Django 6.0.1 on 2026-01-19 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_admin_event_help"),
        ("projects", "0003_adminrecommendation"),
    ]

    operations = []
