# Generated by Django 6.0.1 on 2026-01-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_merge_20260119_2232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminrecommendation",
            name="viewed_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="admin_event_help",
        ),
        migrations.AlterField(
            model_name="adminrecommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("sent", "Envoyée"),
                    ("contacted", "Contacté"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
