# Generated by Django 6.0.1 on 2026-01-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_adminrecommendation_viewed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminrecommendation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recommandation",
                "verbose_name_plural": "Recommandations",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="needs_assistance",
            field=models.BooleanField(
                default=False,
                help_text="Le client souhaite etre accompagne par l'equipe LysAngels",
                verbose_name="Demande d'accompagnement",
            ),
        ),
        migrations.AlterField(
            model_name="adminrecommendation",
            name="admin_note",
            field=models.TextField(
                help_text="Pourquoi ce prestataire est recommandé pour ce projet",
                verbose_name="Note de l'équipe",
            ),
        ),
    ]
