# Generated by Django 6.0.1 on 2026-01-24 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_adminrecommendation_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="needs_assistance",
        ),
        migrations.DeleteModel(
            name="AdminRecommendation",
        ),
    ]
