# Generated by Django 6.0.1 on 2026-04-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_remove_project_needs_assistance_and_more"),
        ("vendors", "0015_remove_subscription_and_user_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Demande client",
                "verbose_name_plural": "Demandes clients",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
        migrations.AddField(
            model_name="project",
            name="contact_email",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="project",
            name="contact_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Nom complet"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Budget minimum (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="project",
            name="event_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de l'événement"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.eventtype",
                verbose_name="Type d'événement",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="services_needed",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="vendors.servicetype",
                verbose_name="Services recherchés",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Nouvelle demande"),
                    ("contacted", "Contacté"),
                    ("in_progress", "En cours"),
                    ("closed", "Clôturé"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
