# Generated by Django 6.0.1 on 2026-01-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("provider", "Prestataire"),
                    ("admin", "Administrateur"),
                ],
                default="client",
                max_length=20,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
