# Generated by Django 6.0.1 on 2026-01-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message au prestataire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('viewed', 'Vue'), ('responded', 'Répondu'), ('declined', 'Refusée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Vue le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_requests', to='projects.project', verbose_name='Projet')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='vendors.vendorprofile', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la proposition')),
                ('message', models.TextField(verbose_name='Message personnalisé')),
                ('description', models.TextField(verbose_name='Description détaillée des services')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix proposé (FCFA)')),
                ('deposit_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Acompte requis (FCFA)')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='Conditions générales')),
                ('validity_days', models.IntegerField(default=30, verbose_name='Validité (jours)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='Fichier joint (PDF, etc.)')),
                ('status', models.CharField(choices=[('sent', 'Envoyée'), ('viewed', 'Vue'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='sent', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Vue le')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Réponse le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.project', verbose_name='Projet')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='vendors.vendorprofile', verbose_name='Prestataire')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='proposals.proposalrequest', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Proposition',
                'verbose_name_plural': 'Propositions',
                'ordering': ['-created_at'],
            },
        ),
    ]
