# Generated by Django 6.0.1 on 2026-01-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Envoyée"),
                    ("viewed", "Vue"),
                    ("accepted", "Acceptée"),
                    ("rejected", "Refusée"),
                ],
                db_index=True,
                default="sent",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="proposalrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="proposalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("viewed", "Vue"),
                    ("responded", "Répondu"),
                    ("declined", "Refusée"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
