# Generated by Django 6.0.1 on 2026-01-19 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_created_by_for_existing_requests(apps, schema_editor):
    """Migrer les données existantes pour définir created_by"""
    ProposalRequest = apps.get_model('proposals', 'ProposalRequest')
    User = apps.get_model('accounts', 'User')
    
    # Récupérer l'admin par défaut
    admin = User.objects.filter(user_type='admin').first()
    
    for pr in ProposalRequest.objects.all():
        if pr.status == 'responded' and admin:
            # Probablement créé par l'admin
            pr.created_by = admin
        else:
            # Créé par le client du projet
            pr.created_by = pr.project.client
        pr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0002_alter_proposal_created_at_alter_proposal_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalrequest",
            name="created_by",
            field=models.ForeignKey(
                help_text="Utilisateur qui a créé cette demande (client ou admin)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_proposal_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.RunPython(set_created_by_for_existing_requests, migrations.RunPython.noop),
    ]
