# Generated by Django 6.0.1 on 2026-05-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("url", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("error_type", models.CharField(db_index=True, max_length=200)),
                ("error_message", models.TextField()),
                ("traceback", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Erreur",
                "verbose_name_plural": "Erreurs",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
