# Generated by Django 6.0.1 on 2026-05-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_error_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_notify_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Reçoit les alertes pour chaque nouveau projet et candidature. Laisser vide pour désactiver.",
                        max_length=254,
                        verbose_name="Email de notification admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres du site",
                "verbose_name_plural": "Paramètres du site",
            },
        ),
    ]
