# Generated by Django 6.0.1 on 2026-01-12 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_termsofservice_usertermsacceptance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "Nouveau message"),
                            ("proposal", "Nouvelle proposition"),
                            ("proposal_status", "Changement statut proposition"),
                            ("request", "Nouvelle demande de devis"),
                            ("request_status", "Changement statut demande"),
                            ("system", "Notification système"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL vers la ressource concernée",
                        max_length=500,
                        verbose_name="Lien",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lu le"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="core_notifi_user_id_f286cd_idx",
                    )
                ],
            },
        ),
    ]
