# Generated by Django 6.0.1 on 2026-01-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Actif"
            ),
        ),
        migrations.AlterField(
            model_name="quartier",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Actif"
            ),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Actif"
            ),
        ),
    ]
