# Generated by Django 6.0.1 on 2026-01-13 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_city_is_active_alter_quartier_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du pays"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code ISO 2 lettres (TG, BJ, GH...)",
                        max_length=2,
                        unique=True,
                        verbose_name="Code ISO",
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 🇹🇬",
                        max_length=10,
                        verbose_name="Drapeau emoji",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["country__name", "name"],
                "verbose_name": "Ville",
                "verbose_name_plural": "Villes",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom de la ville"),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="core.country",
                verbose_name="Pays",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("country", "name")},
        ),
    ]
