# Generated by Django 6.0.1 on 2026-01-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "Nouveau message"),
                    ("proposal", "Nouvelle proposition"),
                    ("proposal_status", "Changement statut proposition"),
                    ("request", "Nouvelle demande de devis"),
                    ("request_status", "Changement statut demande"),
                    ("recommendation", "Recommandation Suzy"),
                    ("project", "Nouveau projet"),
                    ("system", "Notification système"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
