# Generated by Django 6.0.1 on 2026-01-24 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_notification_notification_type"),
        ("vendors", "0014_alter_review_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="core_notifi_user_id_f286cd_idx",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="Quartier",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
