# Generated by Django 6.0.1 on 2026-05-15 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_notification_core_notifi_user_id_f286cd_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserTermsAcceptance",
        ),
    ]
