# Generated by Django 6.0.1 on 2026-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("hero", "Hero homepage"),
                            ("between_sections", "Inter-sections homepage"),
                            ("vendor_list_top", "Top liste prestataires"),
                            ("vendor_detail", "Bas fiche prestataire"),
                        ],
                        max_length=30,
                        verbose_name="Zone",
                    ),
                ),
                ("image", models.ImageField(upload_to="ads/", verbose_name="Image")),
                (
                    "link_url",
                    models.URLField(blank=True, verbose_name="Lien (optionnel)"),
                ),
                (
                    "alt_text",
                    models.CharField(max_length=200, verbose_name="Texte alternatif"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Publicité",
                "verbose_name_plural": "Publicités",
                "ordering": ["-created_at"],
            },
        ),
    ]
