# Generated by Django 6.0.1 on 2026-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="zone",
            field=models.CharField(
                choices=[
                    ("hero", "Hero homepage"),
                    ("between_sections", "Inter-sections homepage"),
                    ("vendor_list_top", "Top liste prestataires"),
                    ("vendor_detail", "Bas fiche prestataire"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Zone",
            ),
        ),
    ]
