# Generated by Django 6.0.1 on 2026-05-15 16:43

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du service"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'icône (ex: camera, music, cake)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Type de service",
                "verbose_name_plural": "Types de services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VendorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom complet")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("whatsapp", models.CharField(max_length=30, verbose_name="WhatsApp")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "description",
                    models.TextField(verbose_name="Description de l'activité"),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instagram"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Facebook"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("contacted", "Contacté"),
                            ("approved", "Approuvé"),
                            ("rejected", "Refusé"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="applications",
                        to="vendors.servicetype",
                        verbose_name="Types de prestation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature prestataire",
                "verbose_name_plural": "Candidatures prestataires",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vendors/logos/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="Logo",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de l'activité"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Adresse (optionnel)"
                    ),
                ),
                (
                    "google_maps_link",
                    models.URLField(blank=True, verbose_name="Lien Google Maps"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Page Facebook")),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Instagram"
                    ),
                ),
                (
                    "min_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget minimum (FCFA)",
                    ),
                ),
                (
                    "max_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget maximum (FCFA)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Profil actif"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Prestataire mis en avant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="core.city",
                        verbose_name="Ville",
                    ),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vendors",
                        to="core.country",
                        verbose_name="Pays d'intervention",
                    ),
                ),
                (
                    "service_types",
                    models.ManyToManyField(
                        related_name="vendors",
                        to="vendors.servicetype",
                        verbose_name="Types de services",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil prestataire",
                "verbose_name_plural": "Profils prestataires",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Taille max: 5MB. Formats: JPEG, PNG, WebP uniquement",
                        upload_to="vendors/",
                        validators=[apps.core.validators.validate_image_file],
                        verbose_name="Image",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False, verbose_name="Image de couverture"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vendors.vendorprofile",
                        verbose_name="Prestataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image prestataire",
                "verbose_name_plural": "Images prestataires",
                "ordering": ["-is_cover", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date du clic"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=40, verbose_name="Session"),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_views",
                        to="vendors.vendorprofile",
                        verbose_name="Prestataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vue coordonnées",
                "verbose_name_plural": "Vues coordonnées",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "viewed_at"],
                        name="vendors_con_vendor__ca1c1a_idx",
                    )
                ],
            },
        ),
    ]
