# Generated by Django 6.0.1 on 2026-01-11 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du service')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: camera, music, cake)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de service',
                'verbose_name_plural': 'Types de services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('description', models.TextField(verbose_name="Description de l'activité")),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('facebook', models.URLField(blank=True, verbose_name='Page Facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget minimum (FCFA)')),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget maximum (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Profil actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Prestataire mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='core.city', verbose_name='Ville')),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='core.quartier', verbose_name='Quartier')),
                ('service_types', models.ManyToManyField(related_name='vendors', to='vendors.servicetype', verbose_name='Types de services')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil prestataire',
                'verbose_name_plural': 'Profils prestataires',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendors/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Image de couverture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendors.vendorprofile', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Image prestataire',
                'verbose_name_plural': 'Images prestataires',
                'ordering': ['-is_cover', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.vendorprofile', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'client')},
            },
        ),
    ]
