# Generated by Django 6.0.1 on 2026-01-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="vendors/logos/", verbose_name="Logo"
            ),
        ),
    ]
