# Generated by Django 6.0.1 on 2026-01-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_vendorprofile_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Profil actif"),
        ),
    ]
