# Generated by Django 6.0.1 on 2026-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("vendors", "0002_vendorapplication_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorapplication",
            name="city",
        ),
        migrations.RemoveField(
            model_name="vendorapplication",
            name="country",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="city",
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="cities",
            field=models.ManyToManyField(
                blank=True,
                related_name="applications",
                to="core.city",
                verbose_name="Villes",
            ),
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="applications",
                to="core.country",
                verbose_name="Pays",
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="cities",
            field=models.ManyToManyField(
                blank=True,
                related_name="vendor_profiles",
                to="core.city",
                verbose_name="Villes d'intervention",
            ),
        ),
    ]
