# Generated by Django 6.0.1 on 2026-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0003_remove_vendorapplication_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorapplication",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name="Adresse / Quartier (optionnel)",
            ),
        ),
    ]
