# Generated by Django 6.0.1 on 2026-01-12 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0003_alter_vendorprofile_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix mensuel (FCFA)",
                    ),
                ),
                (
                    "display_priority",
                    models.IntegerField(
                        default=0,
                        help_text="0 = plus haute priorité (Premium), 1 = Standard, 2 = Gratuit",
                        verbose_name="Priorité d'affichage",
                    ),
                ),
                (
                    "is_visible_in_list",
                    models.BooleanField(
                        default=True,
                        help_text="Si False, visible uniquement lors de recherches",
                        verbose_name="Visible dans la liste par défaut",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "max_images",
                    models.IntegerField(
                        default=10,
                        help_text="Nombre maximum d'images autorisées",
                        verbose_name="Nombre max d'images",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type d'abonnement",
                "verbose_name_plural": "Types d'abonnement",
                "ordering": ["display_priority"],
            },
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="subscription_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'expiration de l'abonnement",
                null=True,
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="subscription_tier",
            field=models.ForeignKey(
                blank=True,
                help_text="Type d'abonnement du prestataire",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendors",
                to="vendors.subscriptiontier",
                verbose_name="Type d'abonnement",
            ),
        ),
    ]
