# Generated by Django 6.0.1 on 2026-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0004_add_address_to_vendor_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="vendorapplication",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=30, verbose_name="WhatsApp"),
        ),
    ]
