# Generated by Django 6.0.1 on 2026-01-12 01:43

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0004_subscriptiontier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorimage",
            name="image",
            field=models.ImageField(
                help_text="Taille maximale: 5MB. Formats acceptés: JPG, PNG, WEBP",
                upload_to="vendors/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Taille maximale: 5MB. Format recommandé: carré (ex: 500x500px)",
                null=True,
                upload_to="vendors/logos/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Logo",
            ),
        ),
    ]
