# Generated by Django 6.0.1 on 2026-05-17 14:20

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0005_email_whatsapp_optional_on_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorapplication",
            name="image_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Photo portfolio 1",
            ),
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Photo portfolio 2",
            ),
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="image_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Photo portfolio 3",
            ),
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="image_4",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Photo portfolio 4",
            ),
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="image_5",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="applications/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Photo portfolio 5",
            ),
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="vendor_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_application",
                to="vendors.vendorprofile",
                verbose_name="Profil créé",
            ),
        ),
    ]
