# Generated by Django 6.0.1 on 2026-01-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendorimage_image_alter_vendorprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Collez le lien de partage de votre localisation Google Maps', verbose_name='Lien Google Maps'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse textuelle si disponible', max_length=300, verbose_name='Adresse (optionnel)'),
        ),
    ]
