# Generated by Django 6.0.1 on 2026-01-12 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("vendors", "0006_vendorprofile_google_maps_link_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="review",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de modération"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_moderated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modéré par",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="moderation_note",
            field=models.TextField(
                blank=True,
                help_text="Raison du rejet si applicable",
                verbose_name="Note de modération",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Projet pour lequel le service a été rendu",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="projects.project",
                verbose_name="Projet",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de modération"),
                    ("approved", "Approuvé"),
                    ("rejected", "Rejeté"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut de modération",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="review",
            name="vendor_response",
            field=models.TextField(blank=True, verbose_name="Réponse du prestataire"),
        ),
        migrations.AddField(
            model_name="review",
            name="vendor_response_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de réponse"
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Note moyenne calculée automatiquement",
                max_digits=3,
                verbose_name="Note moyenne",
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="review_count",
            field=models.IntegerField(
                default=0,
                help_text="Nombre total d'avis approuvés",
                verbose_name="Nombre d'avis",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(
                help_text="Votre avis détaillé sur le prestataire",
                verbose_name="Commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                help_text="Note de 1 à 5 étoiles",
                verbose_name="Note",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("vendor", "project")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["vendor", "status"], name="vendors_rev_vendor__723686_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["client", "created_at"], name="vendors_rev_client__5d0744_idx"
            ),
        ),
    ]
