# Generated by Django 6.0.1 on 2026-05-18

from django.db import migrations

# seed_vendors.py avait créé ces doublons des entrées load_initial_data.py.
# Mapping duplicate_name → canonical_name (conservé).
DUPLICATE_TO_CANONICAL = {
    'Photographie':              'Photographe',
    'Vidéographie':              'Vidéaste',
    'DJ & Animation musicale':   'DJ / Musique',
    'Traiteur & Restauration':   'Traiteur',
    'Décoration & Scénographie': 'Décoration',
    'Fleurs & Art floral':       'Fleuriste',
    'Coiffure & Beauté':         'Maquillage / Coiffure',
    'Maquillage':                'Maquillage / Coiffure',
    'Pâtisserie & Gâteaux':     'Pâtisserie',
    'Animation & Spectacle':     'Animation',
    'Transport & Limousine':     'Transport',
    'Location de salle':         'Salle de réception',
}

# Corrections d'icônes Lucide invalides sur les entrées restantes.
ICON_FIXES = {
    'camera-retro': 'camera',
    'chair':        'armchair',
}


def consolidate(apps, schema_editor):
    ServiceType = apps.get_model('vendors', 'ServiceType')
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    Project = apps.get_model('projects', 'Project')

    for dup_name, canon_name in DUPLICATE_TO_CANONICAL.items():
        try:
            dup = ServiceType.objects.get(name=dup_name)
        except ServiceType.DoesNotExist:
            continue
        try:
            canon = ServiceType.objects.get(name=canon_name)
        except ServiceType.DoesNotExist:
            continue

        for vendor in VendorProfile.objects.filter(service_types=dup):
            vendor.service_types.add(canon)
            vendor.service_types.remove(dup)

        for project in Project.objects.filter(services_needed=dup):
            project.services_needed.add(canon)
            project.services_needed.remove(dup)

        dup.delete()

    for old_icon, new_icon in ICON_FIXES.items():
        ServiceType.objects.filter(icon=old_icon).update(icon=new_icon)


def reverse_consolidate(apps, schema_editor):
    pass  # irréversible — backup avant d'exécuter en production


class Migration(migrations.Migration):
    dependencies = [
        ('vendors', '0006_add_portfolio_images_and_vendor_profile_to_application'),
        ('projects', '0003_email_optional_on_project'),
    ]

    operations = [
        migrations.RunPython(consolidate, reverse_consolidate),
    ]
