# Generated by Django 6.0.1 on 2026-01-13 00:56

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0007_alter_review_unique_together_review_moderated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de modération"),
                    ("approved", "Approuvé"),
                    ("rejected", "Rejeté"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Statut de modération",
            ),
        ),
        migrations.AlterField(
            model_name="vendorimage",
            name="image",
            field=models.ImageField(
                help_text="Taille max: 5MB. Formats: JPEG, PNG, WebP uniquement",
                upload_to="vendors/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Profil actif"
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Prestataire mis en avant"
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Taille max: 5MB. Formats: JPEG, PNG, WebP. Recommandé: carré (500x500px)",
                null=True,
                upload_to="vendors/logos/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Logo",
            ),
        ),
    ]
