# Generated by Django 6.0.1 on 2026-05-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0007_consolidate_service_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorapplication",
            name="business_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom de l'entreprise / marque"
            ),
        ),
    ]
