# Generated by Django 6.0.1 on 2026-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_country_alter_city_options_alter_city_name_and_more"),
        ("vendors", "0008_alter_review_status_alter_vendorimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="countries",
            field=models.ManyToManyField(
                help_text="Pays dans lesquels le prestataire peut intervenir",
                related_name="vendors",
                to="core.country",
                verbose_name="Pays d'intervention",
            ),
        ),
    ]
