# Generated by Django 6.0.1 on 2026-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0008_add_business_name_to_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorapplication",
            name="other_service",
            field=models.CharField(
                blank=True,
                help_text="Si votre activité ne figure pas dans la liste, précisez-la ici.",
                max_length=300,
                verbose_name="Autre prestation (non listée)",
            ),
        ),
    ]
