# Generated by Django 6.0.1 on 2026-05-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0009_add_other_service_to_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Vecteur d'embedding (768 floats). Null = pas encore vectorisé.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="embedding_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vectorisé le"
            ),
        ),
    ]
