# Generated by Django 6.0.1 on 2026-01-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0009_vendorprofile_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="logo",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL de l'image du logo (Cloudinary ou autre)",
                verbose_name="Logo",
            ),
        ),
    ]
