# Generated by Django 6.0.1 on 2026-01-17 20:58

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0010_change_logo_to_urlfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo du prestataire (upload local)",
                null=True,
                upload_to="vendors/logos/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Logo",
            ),
        ),
    ]
