# Generated by Django 6.0.1 on 2026-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0010_vendorprofile_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="search_keywords",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Mots-clés séparés par des virgules (ex: gateau, gâteau, cake, dessert)",
                verbose_name="Mots-clés de recherche",
            ),
        ),
    ]
