# Generated by Django 6.0.1 on 2026-01-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0011_alter_vendorprofile_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="availability_notes",
            field=models.TextField(
                blank=True,
                help_text="Indiquez vos disponibilités (ex: Disponible les weekends, Complet jusqu'à Mars 2025...)",
                verbose_name="Disponibilités",
            ),
        ),
    ]
