# Generated by Django 6.0.1 on 2026-05-19 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0011_add_search_keywords_to_servicetype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorprofile",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="embedding_updated_at",
        ),
    ]
