# Generated by Django 6.0.1 on 2026-05-20 15:31

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    seen = set()
    for vendor in VendorProfile.objects.order_by('id'):
        base = slugify(vendor.business_name) or 'prestataire'
        slug = base
        n = 1
        while slug in seen:
            slug = f"{base}-{n}"
            n += 1
        seen.add(slug)
        vendor.slug = slug
        vendor.save(update_fields=['slug'])


def reverse_slugs(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0012_remove_embedding_from_vendorprofile"),
    ]

    operations = [
        # 1. Add column without any index (db_index=False prevents the _like index on PostgreSQL)
        migrations.AddField(
            model_name="vendorprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                db_index=False,
                help_text="Généré automatiquement depuis le nom de l'entreprise",
                max_length=200,
                verbose_name="Slug URL",
            ),
        ),
        # 2. Populate slugs for existing rows
        migrations.RunPython(populate_slugs, reverse_slugs),
        # 3. Drop the _like index if it exists from a previous failed run (PostgreSQL safety net)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS vendors_vendorprofile_slug_39ea6fd7_like;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 4. Now enforce the unique constraint (creates both the unique B-tree and _like indexes)
        migrations.AlterField(
            model_name="vendorprofile",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Généré automatiquement depuis le nom de l'entreprise",
                max_length=200,
                unique=True,
                verbose_name="Slug URL",
            ),
        ),
    ]
