# Generated by Django 6.0.1 on 2026-01-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0012_vendorprofile_availability_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="availability_notes",
            field=models.TextField(
                blank=True,
                help_text="Informations complémentaires sur vos disponibilités (optionnel)",
                verbose_name="Notes de disponibilité",
            ),
        ),
        migrations.CreateModel(
            name="VendorBlockedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date bloquée")),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Réservé, Congés, Mariage Dupont...",
                        max_length=200,
                        verbose_name="Motif",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_dates",
                        to="vendors.vendorprofile",
                        verbose_name="Prestataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Date bloquée",
                "verbose_name_plural": "Dates bloquées",
                "ordering": ["date"],
                "unique_together": {("vendor", "date")},
            },
        ),
    ]
