# Generated by Django 6.0.1 on 2026-01-24 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0013_add_vendor_blocked_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="vendors_rev_vendor__723686_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="vendors_rev_client__5d0744_idx",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="availability_notes",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="quartier",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="review_count",
        ),
        migrations.RemoveField(
            model_name="review",
            name="client",
        ),
        migrations.RemoveField(
            model_name="review",
            name="moderated_by",
        ),
        migrations.RemoveField(
            model_name="review",
            name="project",
        ),
        migrations.RemoveField(
            model_name="review",
            name="vendor",
        ),
        migrations.DeleteModel(
            name="VendorBlockedDate",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
