# Generated by Django 6.0.1 on 2026-04-04 05:30

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_notification_core_notifi_user_id_f286cd_idx_and_more"),
        ("vendors", "0014_alter_review_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorprofile",
            name="subscription_tier",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="subscription_expires_at",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="address",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Adresse (optionnel)"
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="vendors",
                to="core.country",
                verbose_name="Pays d'intervention",
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="google_maps_link",
            field=models.URLField(blank=True, verbose_name="Lien Google Maps"),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="vendors/logos/",
                validators=[apps.core.validators.validate_image_file],
                verbose_name="Logo",
            ),
        ),
        migrations.DeleteModel(
            name="SubscriptionTier",
        ),
    ]
