# Generated by Django 6.0.1 on 2026-04-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_remove_subscription_and_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du clic')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_views', to='vendors.vendorprofile', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Vue coordonnées',
                'verbose_name_plural': 'Vues coordonnées',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['vendor', 'viewed_at'], name='vendors_con_vendor__ca1c1a_idx')],
            },
        ),
    ]
