# Generated by Django 6.0.1 on 2026-07-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_email_optional_on_project"),
        ("vendors", "0016_extend_vendor_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactview",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_views",
                to="projects.eventtype",
                verbose_name="Type d'événement",
            ),
        ),
    ]
